WITH min5 AS (
    SELECT sum(case when b.st_fascia = '50 Style' then 1 else 0 end)       AS _50Style,
           sum(case when b.st_fascia = 'Action' then 1 else 0 end)         AS Action,
           sum(case when b.st_fascia = 'CCC' then 1 else 0 end)            AS CCC,
           sum(case when b.st_fascia = 'CroppTown' then 1 else 0 end)      AS CroppTown,
           sum(case when b.st_fascia = 'Dealz' then 1 else 0 end)          AS Dealz,
           sum(case when b.st_fascia = 'Deichmann' then 1 else 0 end)      AS Deichmann,
           sum(case when b.st_fascia = 'Diverse' then 1 else 0 end)        AS Diverse,
           sum(case when b.st_fascia = 'Empik' then 1 else 0 end)          AS Empik,
           sum(case when b.st_fascia = 'H&M' then 1 else 0 end)            AS HandM,
           sum(case when b.st_fascia = 'Hebe' then 1 else 0 end)           AS Hebe,
           sum(case when b.st_fascia = 'House' then 1 else 0 end)          AS House,
           sum(case when b.st_fascia = 'Kik' then 1 else 0 end)            AS Kik,
           sum(case when b.st_fascia = 'KS Sport' then 1 else 0 end)       AS KS_Sport,
           sum(case when b.st_fascia = 'Martes Sport' then 1 else 0 end)   AS Martes_Sport,
           sum(case when b.st_fascia = 'Mohito' then 1 else 0 end)         AS Mohito,
           sum(case when b.st_fascia = 'Pepco' then 1 else 0 end)          AS Pepco,
           sum(case when b.st_fascia = 'Reserved' then 1 else 0 end)       AS Reserved,
           sum(case when b.st_fascia = 'Rossmann' then 1 else 0 end)       AS Rossmann,
           sum(case when b.st_fascia = 'SinSay' then 1 else 0 end)         AS SinSay,
           sum(case when b.st_fascia = 'TEDI' then 1 else 0 end)           AS TEDI,
           sum(case when b.st_fascia = 'Aldi' then 1 else 0 end)           AS Aldi,
           sum(case when b.st_fascia = 'Auchan' then 1 else 0 end)         AS Auchan,
           sum(case when b.st_fascia = 'Biedronka' then 1 else 0 end)      AS Biedronka,
           sum(case when b.st_fascia = 'Carrefour' then 1 else 0 end)      AS Carrefour,
           sum(case when b.st_fascia = 'Dino' then 1 else 0 end)           AS Dino,
           sum(case when b.st_fascia = 'Kaufland' then 1 else 0 end)       AS Kaufland,
           sum(case when b.st_fascia = 'Lidl' then 1 else 0 end)           AS Lidl,
           sum(case when b.st_fascia = 'Netto' then 1 else 0 end)          AS Netto,
           sum(case when b.st_fascia = 'Tesco' then 1 else 0 end)          AS Tesco,
           sum(case when b.st_fascia = 'Bricomarche' then 1 else 0 end)    AS Bricomarche,
           sum(case when b.st_fascia = 'Castorama' then 1 else 0 end)      AS Castorama,
           sum(case when b.st_fascia = 'Decathlon' then 1 else 0 end)      AS Decathlon,
           sum(case when b.st_fascia = 'RTV Euro AGD' then 1 else 0 end)   AS RTV_Euro_AGD,
           sum(case when b.st_fascia = 'Leroy Merlin' then 1 else 0 end)   AS Leroy_Merlin,
           sum(case when b.st_fascia = 'MediaExpert' then 1 else 0 end)    AS MediaExpert,
           sum(case when b.st_fascia = 'Media Markt' then 1 else 0 end)    AS Media_Markt,
           sum(case when b.st_fascia = 'Neonet RTV-AGD' then 1 else 0 end) AS Neonet_RTV_AGD,
           sum(case when b.st_fascia = 'Obi' then 1 else 0 end)            AS Obi,
           count(*)                                                        as Total
    FROM mapp.pol_mapp_sites a,
         geodata.pol_glx_geodata_retail_points b
    WHERE ST_INTERSECTS(a.isoline_5min, b.geom_p_4326)
      AND a.id = ${id}
      AND b.st_fascia in (
                          '50 Style',
                          'Action',
                          'CCC',
                          'CroppTown',
                          'Dealz',
                          'Deichmann',
                          'Diverse'
                          'Empik',
                          'H&M',
                          'Hebe',
                          'House',
                          'Kik',
                          'KS Sport',
                          'Martes Sport',
                          'Mohito',
                          'Pepco',
                          'Reserved',
                          'Rossmann',
                          'SinSay',
                          'TEDI',
                          'Aldi',
                          'Auchan',
                          'Biedronka',
                          'Carrefour',
                          'Dino',
                          'Kaufland',
                          'Lidl',
                          'Netto',
                          'Tesco',
                          'Bricomarche',
                          'Castorama',
                          'Decathlon',
                          'RTV Euro AGD',
                          'Leroy Merlin',
                          'MediaExpert',
                          'Media Markt',
                          'Neonet RTV-AGD',
                          'Obi'
        )
),
     min10 AS (
         SELECT sum(case when b.st_fascia = '50 Style' then 1 else 0 end)       AS _50Style,
                sum(case when b.st_fascia = 'Action' then 1 else 0 end)         AS Action,
                sum(case when b.st_fascia = 'CCC' then 1 else 0 end)            AS CCC,
                sum(case when b.st_fascia = 'CroppTown' then 1 else 0 end)      AS CroppTown,
                sum(case when b.st_fascia = 'Dealz' then 1 else 0 end)          AS Dealz,
                sum(case when b.st_fascia = 'Deichmann' then 1 else 0 end)      AS Deichmann,
                sum(case when b.st_fascia = 'Diverse' then 1 else 0 end)        AS Diverse,
                sum(case when b.st_fascia = 'Empik' then 1 else 0 end)          AS Empik,
                sum(case when b.st_fascia = 'H&M' then 1 else 0 end)            AS HandM,
                sum(case when b.st_fascia = 'Hebe' then 1 else 0 end)           AS Hebe,
                sum(case when b.st_fascia = 'House' then 1 else 0 end)          AS House,
                sum(case when b.st_fascia = 'Kik' then 1 else 0 end)            AS Kik,
                sum(case when b.st_fascia = 'KS Sport' then 1 else 0 end)       AS KS_Sport,
                sum(case when b.st_fascia = 'Martes Sport' then 1 else 0 end)   AS Martes_Sport,
                sum(case when b.st_fascia = 'Mohito' then 1 else 0 end)         AS Mohito,
                sum(case when b.st_fascia = 'Pepco' then 1 else 0 end)          AS Pepco,
                sum(case when b.st_fascia = 'Reserved' then 1 else 0 end)       AS Reserved,
                sum(case when b.st_fascia = 'Rossmann' then 1 else 0 end)       AS Rossmann,
                sum(case when b.st_fascia = 'SinSay' then 1 else 0 end)         AS SinSay,
                sum(case when b.st_fascia = 'TEDI' then 1 else 0 end)           AS TEDI,
                sum(case when b.st_fascia = 'Aldi' then 1 else 0 end)           AS Aldi,
                sum(case when b.st_fascia = 'Auchan' then 1 else 0 end)         AS Auchan,
                sum(case when b.st_fascia = 'Biedronka' then 1 else 0 end)      AS Biedronka,
                sum(case when b.st_fascia = 'Carrefour' then 1 else 0 end)      AS Carrefour,
                sum(case when b.st_fascia = 'Dino' then 1 else 0 end)           AS Dino,
                sum(case when b.st_fascia = 'Kaufland' then 1 else 0 end)       AS Kaufland,
                sum(case when b.st_fascia = 'Lidl' then 1 else 0 end)           AS Lidl,
                sum(case when b.st_fascia = 'Netto' then 1 else 0 end)          AS Netto,
                sum(case when b.st_fascia = 'Tesco' then 1 else 0 end)          AS Tesco,
                sum(case when b.st_fascia = 'Bricomarche' then 1 else 0 end)    AS Bricomarche,
                sum(case when b.st_fascia = 'Castorama' then 1 else 0 end)      AS Castorama,
                sum(case when b.st_fascia = 'Decathlon' then 1 else 0 end)      AS Decathlon,
                sum(case when b.st_fascia = 'RTV Euro AGD' then 1 else 0 end)   AS RTV_Euro_AGD,
                sum(case when b.st_fascia = 'Leroy Merlin' then 1 else 0 end)   AS Leroy_Merlin,
                sum(case when b.st_fascia = 'MediaExpert' then 1 else 0 end)    AS MediaExpert,
                sum(case when b.st_fascia = 'Media Markt' then 1 else 0 end)    AS Media_Markt,
                sum(case when b.st_fascia = 'Neonet RTV-AGD' then 1 else 0 end) AS Neonet_RTV_AGD,
                sum(case when b.st_fascia = 'Obi' then 1 else 0 end)            AS Obi,
                count(*)                                                        as Total
         FROM mapp.pol_mapp_sites a,
              geodata.pol_glx_geodata_retail_points b
         WHERE ST_INTERSECTS(a.isoline_10min, b.geom_p_4326)
           AND a.id = ${id}
           AND b.st_fascia in (
                               '50 Style',
                               'Action',
                               'CCC',
                               'CroppTown',
                               'Dealz',
                               'Deichmann',
                               'Diverse',
                               'Empik',
                               'H&M',
                               'Hebe',
                               'House',
                               'Kik',
                               'KS Sport',
                               'Martes Sport',
                               'Mohito',
                               'Pepco',
                               'Reserved',
                               'Rossmann',
                               'SinSay',
                               'TEDI',
                               'Aldi',
                               'Auchan',
                               'Biedronka',
                               'Carrefour',
                               'Dino',
                               'Kaufland',
                               'Lidl',
                               'Netto',
                               'Tesco',
                               'Bricomarche',
                               'Castorama',
                               'Decathlon',
                               'RTV Euro AGD',
                               'Leroy Merlin',
                               'MediaExpert',
                               'Media Markt',
                               'Neonet RTV-AGD',
                               'Obi'
             )
     ),
     min15 AS (
         SELECT sum(case when b.st_fascia = '50 Style' then 1 else 0 end)       AS _50Style,
                sum(case when b.st_fascia = 'Action' then 1 else 0 end)         AS Action,
                sum(case when b.st_fascia = 'CCC' then 1 else 0 end)            AS CCC,
                sum(case when b.st_fascia = 'CroppTown' then 1 else 0 end)      AS CroppTown,
                sum(case when b.st_fascia = 'Dealz' then 1 else 0 end)          AS Dealz,
                sum(case when b.st_fascia = 'Deichmann' then 1 else 0 end)      AS Deichmann,
                sum(case when b.st_fascia = 'Diverse' then 1 else 0 end)        AS Diverse,
                sum(case when b.st_fascia = 'Empik' then 1 else 0 end)          AS Empik,
                sum(case when b.st_fascia = 'H&M' then 1 else 0 end)            AS HandM,
                sum(case when b.st_fascia = 'Hebe' then 1 else 0 end)           AS Hebe,
                sum(case when b.st_fascia = 'House' then 1 else 0 end)          AS House,
                sum(case when b.st_fascia = 'Kik' then 1 else 0 end)            AS Kik,
                sum(case when b.st_fascia = 'KS Sport' then 1 else 0 end)       AS KS_Sport,
                sum(case when b.st_fascia = 'Martes Sport' then 1 else 0 end)   AS Martes_Sport,
                sum(case when b.st_fascia = 'Mohito' then 1 else 0 end)         AS Mohito,
                sum(case when b.st_fascia = 'Pepco' then 1 else 0 end)          AS Pepco,
                sum(case when b.st_fascia = 'Reserved' then 1 else 0 end)       AS Reserved,
                sum(case when b.st_fascia = 'Rossmann' then 1 else 0 end)       AS Rossmann,
                sum(case when b.st_fascia = 'SinSay' then 1 else 0 end)         AS SinSay,
                sum(case when b.st_fascia = 'TEDI' then 1 else 0 end)           AS TEDI,
                sum(case when b.st_fascia = 'Aldi' then 1 else 0 end)           AS Aldi,
                sum(case when b.st_fascia = 'Auchan' then 1 else 0 end)         AS Auchan,
                sum(case when b.st_fascia = 'Biedronka' then 1 else 0 end)      AS Biedronka,
                sum(case when b.st_fascia = 'Carrefour' then 1 else 0 end)      AS Carrefour,
                sum(case when b.st_fascia = 'Dino' then 1 else 0 end)           AS Dino,
                sum(case when b.st_fascia = 'Kaufland' then 1 else 0 end)       AS Kaufland,
                sum(case when b.st_fascia = 'Lidl' then 1 else 0 end)           AS Lidl,
                sum(case when b.st_fascia = 'Netto' then 1 else 0 end)          AS Netto,
                sum(case when b.st_fascia = 'Tesco' then 1 else 0 end)          AS Tesco,
                sum(case when b.st_fascia = 'Bricomarche' then 1 else 0 end)    AS Bricomarche,
                sum(case when b.st_fascia = 'Castorama' then 1 else 0 end)      AS Castorama,
                sum(case when b.st_fascia = 'Decathlon' then 1 else 0 end)      AS Decathlon,
                sum(case when b.st_fascia = 'RTV Euro AGD' then 1 else 0 end)   AS RTV_Euro_AGD,
                sum(case when b.st_fascia = 'Leroy Merlin' then 1 else 0 end)   AS Leroy_Merlin,
                sum(case when b.st_fascia = 'MediaExpert' then 1 else 0 end)    AS MediaExpert,
                sum(case when b.st_fascia = 'Media Markt' then 1 else 0 end)    AS Media_Markt,
                sum(case when b.st_fascia = 'Neonet RTV-AGD' then 1 else 0 end) AS Neonet_RTV_AGD,
                sum(case when b.st_fascia = 'Obi' then 1 else 0 end)            AS Obi,
                count(*)                                                        as Total
         FROM mapp.pol_mapp_sites a,
              geodata.pol_glx_geodata_retail_points b
         WHERE ST_INTERSECTS(a.isoline_15min, b.geom_p_4326)
           AND a.id = ${id}
           AND b.st_fascia in (
                               '50 Style',
                               'Action',
                               'CCC',
                               'CroppTown',
                               'Dealz',
                               'Deichmann',
                               'Diverse',
                               'Empik',
                               'H&M',
                               'Hebe',
                               'House',
                               'Kik',
                               'KS Sport',
                               'Martes Sport',
                               'Mohito',
                               'Pepco',
                               'Reserved',
                               'Rossmann',
                               'SinSay',
                               'TEDI',
                               'Aldi',
                               'Auchan',
                               'Biedronka',
                               'Carrefour',
                               'Dino',
                               'Kaufland',
                               'Lidl',
                               'Netto',
                               'Tesco',
                               'Bricomarche',
                               'Castorama',
                               'Decathlon',
                               'RTV Euro AGD',
                               'Leroy Merlin',
                               'MediaExpert',
                               'Media Markt',
                               'Neonet RTV-AGD',
                               'Obi'
             )
     )
SELECT UNNEST(ARRAY [
    '50 Style',
    'Action',
    'CCC',
    'CroppTown',
    'Dealz',
    'Deichmann',
    'Diverse',
    'Empik',
    'H&M',
    'Hebe',
    'House',
    'Kik',
    'KS Sport',
    'Martes Sport',
    'Mohito',
    'Pepco',
    'Reserved',
    'Rossmann',
    'SinSay',
    'TEDI',
    'Aldi',
    'Auchan',
    'Biedronka',
    'Carrefour',
    'Dino',
    'Kaufland',
    'Lidl',
    'Netto',
    'Tesco',
    'Bricomarche',
    'Castorama',
    'Decathlon',
    'RTV Euro AGD',
    'Leroy Merlin',
    'MediaExpert',
    'Media Markt',
    'Neonet RTV-AGD',
    'Obi',
    'Total'
    ]
           ) AS rows,
       UNNEST(
               ARRAY [
                   min5._50Style,
                   min5.Action,
                   min5.CCC,
                   min5.CroppTown,
                   min5.Dealz,
                   min5.Deichmann,
                   min5.Diverse,
                   min5.Empik,
                   min5.HandM,
                   min5.Hebe,
                   min5.House,
                   min5.Kik,
                   min5.KS_Sport,
                   min5.Martes_Sport,
                   min5.Mohito,
                   min5.Pepco,
                   min5.Reserved,
                   min5.Rossmann,
                   min5.SinSay,
                   min5.TEDI,
                   min5.Aldi,
                   min5.Auchan,
                   min5.Biedronka,
                   min5.Carrefour,
                   min5.Dino,
                   min5.Kaufland,
                   min5.Lidl,
                   min5.Netto,
                   min5.Tesco,
                   min5.Bricomarche,
                   min5.Castorama,
                   min5.Decathlon,
                   min5.RTV_Euro_AGD,
                   min5.Leroy_Merlin,
                   min5.MediaExpert,
                   min5.Media_Markt,
                   min5.Neonet_RTV_AGD,
                   min5.Obi,
                   min5.Total
                   ]
           ) AS min5,
       UNNEST(
               ARRAY [
                   min10._50Style,
                   min10.Action,
                   min10.CCC,
                   min10.CroppTown,
                   min10.Dealz,
                   min10.Deichmann,
                   min10.Diverse,
                   min10.Empik,
                   min10.HandM,
                   min10.Hebe,
                   min10.House,
                   min10.Kik,
                   min10.KS_Sport,
                   min10.Martes_Sport,
                   min10.Mohito,
                   min10.Pepco,
                   min10.Reserved,
                   min10.Rossmann,
                   min10.SinSay,
                   min10.TEDI,
                   min10.Aldi,
                   min10.Auchan,
                   min10.Biedronka,
                   min10.Carrefour,
                   min10.Dino,
                   min10.Kaufland,
                   min10.Lidl,
                   min10.Netto,
                   min10.Tesco,
                   min10.Bricomarche,
                   min10.Castorama,
                   min10.Decathlon,
                   min10.RTV_Euro_AGD,
                   min10.Leroy_Merlin,
                   min10.MediaExpert,
                   min10.Media_Markt,
                   min10.Neonet_RTV_AGD,
                   min10.Obi,
                   min10.Total
                   ]
           ) AS min10,
       UNNEST(
               ARRAY [
                   min15._50Style,
                   min15.Action,
                   min15.CCC,
                   min15.CroppTown,
                   min15.Dealz,
                   min15.Deichmann,
                   min15.Diverse,
                   min15.Empik,
                   min15.HandM,
                   min15.Hebe,
                   min15.House,
                   min15.Kik,
                   min15.KS_Sport,
                   min15.Martes_Sport,
                   min15.Mohito,
                   min15.Pepco,
                   min15.Reserved,
                   min15.Rossmann,
                   min15.SinSay,
                   min15.TEDI,
                   min15.Aldi,
                   min15.Auchan,
                   min15.Biedronka,
                   min15.Carrefour,
                   min15.Dino,
                   min15.Kaufland,
                   min15.Lidl,
                   min15.Netto,
                   min15.Tesco,
                   min15.Bricomarche,
                   min15.Castorama,
                   min15.Decathlon,
                   min15.RTV_Euro_AGD,
                   min15.Leroy_Merlin,
                   min15.MediaExpert,
                   min15.Media_Markt,
                   min15.Neonet_RTV_AGD,
                   min15.Obi,
                   min15.Total
                   ]
           ) AS min15
       
FROM min5,
     min10,
     min15;